# Generated by Django 3.2.6 on 2021-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstyearform',
        ),
    ]
