# Generated by Django 3.2.6 on 2021-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GGDC', '0002_delete_firstyearform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='faculty/')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('department', models.CharField(blank=True, choices=[('Zoology', 'Zoology'), ('Physics', 'Physics'), ('Botany', 'Botany'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('English', 'English')], max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('Associate professor', 'Associate professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Visiting', 'Visiting'), ('Lab Assistant', 'Lab Assistant')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired')], max_length=30, null=True)),
            ],
        ),
    ]
