# Generated by Django 3.2.6 on 2021-10-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0003_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
