# Generated by Django 3.2.6 on 2021-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GGDC', '0004_delete_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='faculty/')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('hod', models.CharField(blank=True, choices=[('HOD', 'HOD')], max_length=20, null=True)),
                ('department', models.CharField(choices=[('BBA', 'BBA'), ('Botany', 'Botany'), ('BSIT', 'BSIT'), ('Commerce', 'Commerce'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('English', 'English'), ('Home Economics', 'Home Economics'), ('Mathematics', 'Mathematics'), ('Pakistan Studies', 'Pakistan Studies'), ('Physical Education', 'Physical Education'), ('Physics', 'Physics'), ('Sindhi', 'Sindhi'), ('Urdu', 'Urdu'), ('Zoology', 'Zoology')], max_length=50)),
                ('designation', models.CharField(choices=[('Associate professor', 'Associate professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Visiting', 'Visiting'), ('Lab Assistant', 'Lab Assistant')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Retired', 'Retired')], max_length=30)),
            ],
        ),
    ]
