# Generated by Django 3.2.6 on 2021-10-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0006_auto_20211011_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='principal/')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Former', 'Former')], max_length=30)),
            ],
        ),
    ]
