# Generated by Django 3.2.6 on 2021-10-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0007_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_upload', models.FileField(upload_to='media')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('BSIT', 'BSIT'), ('BBA', 'BBA')], max_length=50)),
            ],
        ),
    ]
