# Generated by Django 3.2.6 on 2021-10-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0008_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('dec', models.CharField(max_length=500)),
                ('date_uploaded', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='admin_upload',
            field=models.FileField(upload_to='books'),
        ),
    ]
