# Generated by Django 3.2.6 on 2021-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0010_alter_books_admin_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='achievements/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=100)),
                ('dec', models.CharField(max_length=700)),
                ('date', models.DateField()),
                ('date_uploaded', models.DateField()),
                ('status', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_uploaded', models.DateField()),
            ],
        ),
    ]
