# Generated by Django 3.2.6 on 2021-10-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0011_achievements_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
