# Generated by Django 3.2.9 on 2021-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0012_delete_achievements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstyearform',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='std_doc/')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christen', 'Christen'), ('Other', 'Other')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=50)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('permanent_address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('talukka', models.CharField(max_length=100)),
                ('postal_address', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('guardian_cnumber', models.IntegerField()),
                ('guardian_profession', models.CharField(max_length=100)),
                ('family_members', models.IntegerField()),
                ('Guardian_mlyincome', models.IntegerField()),
                ('native_place', models.CharField(max_length=100)),
                ('cnic_no', models.IntegerField()),
                ('cnic_img', models.ImageField(upload_to='std_doc/')),
                ('vaccination_img', models.ImageField(upload_to='std_doc/')),
                ('slip_img', models.ImageField(upload_to='std_doc/')),
                ('ssc_max_marks', models.IntegerField()),
                ('ssc_obt_marks', models.IntegerField()),
                ('ssc_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('ssc_passing_year', models.IntegerField()),
                ('ssc_seat_number', models.IntegerField()),
                ('ssc_status', models.CharField(choices=[('Annual', 'Annual'), ('Supply', 'supply')], max_length=50)),
                ('ssc_board', models.CharField(choices=[('BISE Sukkur Board', 'BISE Sukkur Board'), ('Panjab Board', 'Panjab Board'), ('Agha Khan Board', 'Agha Khan Board'), ('Cambridge', 'Cambridge')], max_length=50)),
                ('hsc1_max_marks', models.IntegerField(blank=True)),
                ('hsc1_obt_marks', models.IntegerField(blank=True)),
                ('hsc1_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('hsc1_passing_year', models.IntegerField(blank=True)),
                ('hsc1_seat_number', models.IntegerField(blank=True)),
                ('hsc1_status', models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Supply', 'supply')], max_length=50)),
                ('hsc1_board', models.CharField(blank=True, choices=[('BISE Sukkur Board', 'BISE Sukkur Board'), ('Panjab Board', 'Panjab Board'), ('Agha Khan Board', 'Agha Khan Board'), ('Cambridge', 'Cambridge')], max_length=50)),
            ],
        ),
    ]
