# Generated by Django 3.2.9 on 2021-11-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0013_firstyearform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_board',
            field=models.CharField(blank=True, choices=[('BISE Sukkur Board', 'BISE Sukkur Board'), ('Panjab Board', 'Panjab Board'), ('Agha Khan Board', 'Agha Khan Board'), ('Cambridge', 'Cambridge')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_obt_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstyearform',
            name='hsc1_status',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Supply', 'supply')], max_length=50, null=True),
        ),
    ]
