# Generated by Django 3.2.9 on 2021-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGDC', '0014_auto_20211122_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('BBA', 'BBA'), ('Botany', 'Botany'), ('BSIT', 'BSIT'), ('Commerce', 'Commerce'), ('Chemistry', 'Chemistry'), ('Economics', 'Economics'), ('English', 'English'), ('Home Economics', 'Home Economics'), ('Islamiat', 'Islamiat'), ('Mathematics', 'Mathematics'), ('Pakistan Studies', 'Pakistan Studies'), ('Physical Education', 'Physical Education'), ('Physics', 'Physics'), ('Sindhi', 'Sindhi'), ('Urdu', 'Urdu'), ('Zoology', 'Zoology')], max_length=50),
        ),
    ]
